API.getComments(int bookId);
Zekfad/nhentai_dart pull request #3
Opened 2022-07-23 18:45 UTC by LacticWhale

2022-07-23 19:31 UTC, Zekfad requested changes
Whole `avatar url` stuff isn't needed.
They all follow same rules: `avatars/${userId}.png` or `avatars/pastamania.png`
Make it either `avatarFilename` or `boolean` `hasAvatar`, and add to `getAvatarUrl` named parameter `fallback` with default value `pastamania.png`.

> One is a general solution, the other is memory efficient.
> I guess it's better to stick with filename.



Also add `getAvatarUrl` to `User` like that: https://github.com/Zekfad/nhentai_dart/blob/5bb4fa77477af8b7963d1d610403ff8b1f655d43/lib/src/Image.dart#L106-L114

2022-07-23 19:31 UTC, Zekfad commented on lib/src/API.dart
> +  Uri getAvatarUrl(String avatarUrl) => Uri.https(
This function must accept `User` not a `String`.

2022-07-23 19:31 UTC, Zekfad commented on lib/src/API.dart
> +      _getJson(_getPath(HostType.api, '/api/gallery/$bookId/comments')),
Place `_getPath` on a new line, please.

2022-07-23 19:31 UTC, Zekfad commented on lib/src/API.dart
> +  Uri getAvatarUrl(String avatarUrl) => hosts.getAvatarUrl(avatarUrl);
This function must accept `User` not a `String`.

2022-07-23 19:31 UTC, Zekfad commented on lib/src/API.dart
> +  Uri getAvatarUrl(String avatarUrl) => hosts.getAvatarUrl(avatarUrl);
Place this function after `getImageUrl`.

2022-07-23 19:31 UTC, Zekfad commented on lib/src/User.dart
> +  final bool isStaff;
Drop `is`.

2022-07-23 19:31 UTC, Zekfad commented on lib/src/Comment.dart
> +  final User poster;
Name it `user`.

2022-07-23 19:31 UTC, Zekfad commented on lib/src/Comment.dart
> +  final int galleryId;
Name it `bookId`.

2022-07-23 19:31 UTC, Zekfad commented on lib/src/Comment.dart
> +  Comment({
This class is const.

2022-07-23 19:31 UTC, Zekfad commented on lib/src/User.dart
> +  User({
This class is const.

2022-07-23 20:19 UTC, Zekfad requested changes

2022-07-23 20:19 UTC, Zekfad commented on lib/src/API.dart
> +    user.avatarFilename,
That's wrong.

2022-07-26 21:07 UTC, Zekfad requested changes
Some changes required.

2022-07-26 21:07 UTC, Zekfad commented on lib/src/API.dart
> +  /// Get user avatar url with respect to this client instance [hosts] settings.
Mark `user` as `[user]` in docs.

2022-07-26 21:07 UTC, Zekfad commented on lib/src/API.dart
> +  /// Get user avatar url with respect to this client instance [hosts] settings.
Change to "with respect to [hosts] settings", please.

2022-07-26 21:07 UTC, Zekfad commented on lib/src/User.dart
>    /// Is user a stuff.
Change to "Whether user is staff member", please.

2022-07-26 21:07 UTC, Zekfad commented on lib/src/User.dart
> +  Uri getAvatarUrl({
Add docs.
Example:
https://github.com/Zekfad/nhentai_dart/blob/dba010658c2b965f77d91e4e501d58edb654db7c/lib/src/Image.dart#L105-L109

2022-07-26 21:07 UTC, Zekfad commented on lib/src/User.dart
> +    if(json == null)
Space after `if`.

2022-07-26 21:07 UTC, Zekfad commented on pubspec.yaml
> +  http: ^0.13.4
?

2022-07-26 21:07 UTC, Zekfad commented on lib/src/API.dart
> +
Remove 1 newline.

2022-07-26 21:07 UTC, Zekfad commented on lib/src/Comment.dart
> +    if(json == null)
Space after `if`.

2022-07-26 21:07 UTC, Zekfad commented on lib/src/Comment.dart
> +  /// Get [body].
"Get comment [body]".

2022-07-26 21:07 UTC, Zekfad commented on lib/src/User.dart
> +  /// User slug.
"User slug (unique short username for URLs)"

2022-07-26 21:07 UTC, Zekfad commented on lib/src/User.dart
> +  /// Is user a superuser.
"Whether user is superuser"

2022-07-26 21:07 UTC, Zekfad commented on lib/src/User.dart
> +  /// User relevant avatar path.
"User's avatar file name"

2022-07-26 21:07 UTC, Zekfad commented on lib/src/API.dart
> +  /// Get comments associated with given book ID.
"Get book comments"

2022-07-26 21:07 UTC, Zekfad commented on lib/src/Comment.dart
> +  final int bookId;
"Gallery" -> "Book"

2022-07-26 21:09 UTC, LacticWhale commented on pubspec.yaml
> +  http: ^0.13.4
bruh

2022-07-31 16:58 UTC, Zekfad requested changes

2022-07-31 16:58 UTC, Zekfad commented on lib/src/User.dart
> +    if(json == null)
still

2022-07-31 18:18 UTC, Zekfad approved these changes

2022-07-31 18:19 UTC, merged